# Lancer l'application avec docker compose up –build
version: '3'

services:
  web:
    build: .
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    volumes:
      - .:/appp
    env_file:
      - .env
    # ou utiliser des variables inline (même si c'est moins pratique pour gérer la prod):
    # environment:
    #   - SECRET_KEY=${SECRET_KEY}
    #   - DATABASE_URL=${DATABASE_URL}